### PR TITLE
Mention the new `ga4` plugin

### PR DESCRIPTION
**Pull request by paulca**
PR for an update to the docs mentioning the `ga4` plugin and deprecating the existing ones.

### CODE REVIEW

**Review by billhorsman — APPROVED** [review]
🚢

**Comment by paulca** [comment]
@billhorsman Does this auto-deploy?

**Comment by billhorsman** [comment]
> @billhorsman Does this auto-deploy?

Only to staging. Production needs a manual deploy. Want me to do it?

**Comment by paulca** [comment]
@billhorsman Yes please. Thank you!

**Pull request merged**
