### PR TITLE
Make sure we document all the plugins

### PR DESCRIPTION
**Pull request by billhorsman**
> As an organiser, I want to know how to use all the plugins.

CleanShot 2021-06-10 at 11 31 07@2x

# Intercom Help Docs

The [Google Analytics article on Intercom](https://app.intercom.com/a/apps/nhi52s19/articles/articles/2006249/show) needs bringing up to date as well.

- [x] ~I think the `google_analytics` plugin mentioned should be `ga`?~ `ga` is obsolete
- [x] Should we add information there about tracking the `tito:checkout` and `tito:purchase` events?

### CODE REVIEW

**Comment by paulca** [comment]
@billhorsman The `ga` implementation of Google Analytics is referred to as "[Analytics.js](https://developers.google.com/analytics/devguides/collection/analyticsjs/)". I didn't want to call it `analytics` because that just seemed too generic, so that's why I went with `google_analtics`. Google refer to gtag as gtag.js. Arguably `gtm` should be `google_tag_manager` because that's what [Google calls it](https://developers.google.com/tag-manager/quickstart). I think it's probably fine the way it is.

I think we should refer to the tracked events, yes.

**Comment by paulca** [comment]
(At least mentioning them for now would be good)

**Comment by paulca** [comment]
(Sorry I accidentally closed this)

**Comment by billhorsman** [comment]
@paulca I'm happy with `google_analytics` but the file in `js-tito` is called `ga.js` so we either need to call the plugin `ga` or rename the file to `google_analytics.js`, right?

**Comment by billhorsman** [comment]
I've also just added a link to the widget from the index:

CleanShot 2021-06-10 at 11 53 24@2x

**Comment by paulca** [comment]
@billhorsman Very cool. We must be pretty close to being able to document the checkout API at this stage, right?

**Review by paulca — APPROVED** [review]
These are all very good improvements.

**Pull request merged**
